# common params
batch: 128
epochs: 2
#bpe: false

# learning rate
lr: 0.0001
# betas: [0.9, 0.98]
beta-min: 0.9
beta-max: 0.98
eps: 1e-9

# gradient explosion treatment
clip: 1

# data params
min-freq: 3

# encoder - decoder params
enc-emb-dim: 256
dec-emb-dim: 256
hid-dim: 512
n-layers: 2
enc-dropout: 0.5
dec-dropout: 0.5

enc-type: rnn
dec-type: rnn
seq2seq-type: rnn
seq2seq-name: Seq2Seq
enc-name: Encoder
dec-name: Decoder


teacher-forcing-ratio: 0.5

# transformer params
nhead: 8
ffn-hid-dim: 512
num-encoder-layers: 3
num-decoder-layers: 3
emb_size: 512
